pelican-plugins/photos

CHANGELOG.md

The release bot adds an empty line at the end of the changelog file. This is not valid to pass the CI pipeline. This PR fixes the issue.

Fix autogenerated changelog to pass ci pipeline

---

README.md
pelican/plugins/photos/photos.py

Use the new config value to provide additional options to the pillow image writer.

Add config value for image options

---

README.md
pelican/plugins/photos/photos.py

- In some situations multiprocessing does not work if there is at least
one value in the pelican config that can't be pickled. We fix it by
using a global variable to hold the config.
- Add option to detect cpu count and start parallel resize processes
- Add documentation

Use global config and detect cpu count

---

pelican/plugins/photos/photos.py

This fixes an error if we try to access image information before it is processed.

Process images before writing any content

---

pelican/plugins/photos/photos.py

Allows to use multiple profiles on the same image without naming conflicts.

Add file_suffix to profile

---

.github/workflows/main.yml
pyproject.toml

Some CVEs have been fixed in Pillow 8.3.x and 9.0.x so we bump the version from 8.2 to 9.0.1+
See: https://github.com/python-pillow/Pillow/blob/main/CHANGES.rst
This fixes #46

Bump dependency Pillow to 9.0.1+

---

pelican/plugins/photos/photos.py

- If the gallery path ends with an / it will be added to the image path and results in a path with double // like ```gallery/name//image.jpg``` instead of ```gallery/name/image.jpg```
- Add __repr__ function to image class

Fix issue with wrong gallery path

---

pelican/plugins/photos/photos.py

The configurations in these defaults are converted to a dict with an INFO logged warning shortly after setting these defaults, so this change removes some spurious logging due to the legacy default values

Update the default gallery, article, and thumb config

---

.github/workflows/main.yml

This eliminates the need for a manually managed GH_TOKEN secret; the only scope needed by autopub[github] is the `repo` scope, which is covered by `contents: write` in the workflow

Switch to using the repository token for release creation

---

.github/workflows/main.yml
pyproject.toml
tasks.py

This PR introduces, but _very much_ does not require running `ruff` as a
linter (since that spits out a *large* number of violations)

Update the pelican-photos build to use pdm+hatchling

---

RELEASE.md
pyproject.toml

Due to [security issues](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.1.html) in Pillow package, we must bump the minimum required version.
As a consequence, we must also bump the minimum python version to v3.8 because pillow v10.0.1 requires python v3.8 at minimum.
This commit will improve the overall security and future maintenance of pelican-photos plugin.

Increment Pillow minimum version to address security issue

---

.github/workflows/main.yml
pelican/plugins/photos/photos.py

Previously, Python 3.10 was hardcoded in the `tests` CI job, causing the test matrix to use that same 3.10 version even for test runs labeled with 3.8, 3.9, 3.11, and 3.12.
This fixes that problem, seemingly unearthing a test error on Python 3.8 related to recently-applied Ruff formatting. (cc: @offbyone)

Actually use Python version matrix in CI tests

---

pyproject.toml

Also, separate the rest into dependency groups and set minimum versions.

Remove unneeded dev dependencies

---

.github/workflows/main.yml

Until either (1) the `githubrelease` project ships a new release with the fix we need, or (2) the `githubrelease` module is vendored into AutoPub itself, we need this temporary measure to use the implicit `GITHUB_TOKEN` environment variable.
Related issues:
- https://github.com/pelican-plugins/photos/pull/99
- https://github.com/j0057/github-release/pull/73
- https://github.com/autopub/autopub/issues/42

Use forked `githubrelease` as temporary CI fix

---

pelican/plugins/photos/photos.py

If the image is to small for the watermark text the calculated font size is 0. This results in an error with newer pillow versions. See #110

Fix issue with font size to small

---

pelican/plugins/photos/photos.py

We render our own templates so we have to add the SITEURL var to the context. This fixes #87

Add SITEURL to template context

---

pelican/plugins/photos/photos.py

Template from examples/ sets image path as \{\{ SITEURL \}\}/\{\{ photo \}\} however it wasn't replaced.
My solution is extremely simple and rather not dedicated for production work so feel free to close my PR and fix this someway else

photos: eplace SITEURL in template of inline_gallery.html

---

examples/content/pages/page-with-gallery.md
examples/content/pages/page-with-image.md
examples/content/pages/page-with-inline-gallery.md
examples/content/pages/page-with-inline-image.md
examples/pelicanconf.py
examples/themes/notmyidea_photos/templates/article.html
examples/themes/notmyidea_photos/templates/inline_gallery.html
examples/themes/notmyidea_photos/templates/inline_image.html
examples/themes/notmyidea_photos/templates/lightbox_gallery.html
examples/themes/notmyidea_photos/templates/page.html
examples/themes/notmyidea_photos/templates/photos_macros.html

Add examples how to use this plugin with pages.
Remove the lorem ipsum text from the examples to focus on the documentation and how to use the plugin.

Add more examples and remove lorem ipsum text

---

.pre-commit-config.yaml
pelican/plugins/photos/photos.py
pyproject.toml

Some code changes are needed to comply with Ruff 0.3.x, but those changes make the code less readable, so I added `NOQA` exceptions for those two spots.

Upgrade Ruff linter

---

pelican/plugins/photos/photos.py

Some plugins like the i18n subsites plugin change the settings or the output path to generate different pages for different languages. We only use the first output path and reuse the images for all languages.
Refs #93

Use only the first output path we get
