pelican-plugins/photos

README.md, pelican/plugins/photos/photos.py, pelican/plugins/photos/test_photos.py
Add support for inline galleries. Refs #3
=> Restructure code and add inline galleries

pelican/plugins/photos/photos.py, pelican/plugins/photos/test_photos.py
Instead of static tuples/lists we use classes to handle image information.
=> Rewrite to use classes

pelican/plugins/photos/photos.py, pelican/plugins/photos/test_photos.py
Add additional information like width and height to the Image object to use it later in the template. Also improve error handling for multiprocessing.
=> Image info

docs/Makefile, docs/api.rst, docs/conf.py, docs/index.rst, docs/make.bat, docs/requirements.txt, pelican/plugins/photos/photos.py, pelican/plugins/photos/test_photos.py
Refactor the code and add some internal documentation.
=> Refactor code and add doc

RELEASE.md
Prepare the next minor release.
=> Prepare new release

README.md, pelican/plugins/photos/photos.py
Add option to calculate the average color for an image. This can be used as background color while lazy loading the images.
=> Average color

pelican/plugins/photos/photos.py
With this option it is possible to generate blurred images for lazy
loading.
=> Add config parameter to generate addtional images

pelican/plugins/photos/photos.py
This changes how the image operations are processed. We add a list the user can modify and we can add additional operations in the future.
=> Operations

examples/themes/notmyidea_photos/templates/article.html, pelican/plugins/photos/photos.py, pelican/plugins/photos/test_photos.py
- Add support for image profiles
- Add improved support for inline images and galleries
- Update signal handling for improved processing
=> Image profiles and more

pelican/plugins/photos/photos.py
Add option to make some images available for all pages and articles.
=> Add support for global images

pelican/plugins/photos/photos.py
- Change how operations are processed
- Add new operations:
- convert
- convert_mode_p
- quantize
=> Image operations

pelican/plugins/photos/photos.py
Add additional images in the article metadata.
=> Add support for named images in metadata

pelican/plugins/photos/photos.py
The global var could be used in any template
=> Add processed global images to list to be used in templates

pelican/plugins/photos/photos.py
=> Show more details if profile is missing

pelican/plugins/photos/photos.py
- We did not process all pages and all articles, like draft translations
or hidden articles
- This commit adds supports for published, hidden and draft articles and
pages and also for there translations
=> Generate images for status hidden

pelican/plugins/photos/photos.py
=> Remove print

pelican/plugins/photos/photos.py
Just a quick fix to improve caption handling and caching
=> Improve caption handling and caching

pelican/plugins/photos/photos.py
- Raise exception if unable to detect mime type
- Skip subdirectories in galleries
- Raise exception and skip file if it is not an image
Fixes  #50
=> Error handling

pelican/plugins/photos/photos.py
- Process exif data
- Rotate images according to information from exif (Fixes #49 )
- Add original icc_profile to result image
=> Handle image info

pelican/plugins/photos/photos.py
- Some links are broken if SITEURL is not set, this should be fixed with
the change
This fixes #51
=> Use urljoin and add / to prevent errors

README.md, pelican/plugins/photos/photos.py
- Add option for profiling some function calls
- Replace local pool to global process pool - In our tests this speeds up processing
=> Profiling and pooling

pelican/plugins/photos/photos.py
There was an error on Mac Systems with profiling and multiprocessing. This should fix this issue.
=> Fix some minor issues with multiprocessing

pelican/plugins/photos/photos.py, pelican/plugins/photos/test_photos.py
At the moment only the fork mode on Linux works as expected. This changes adds support for the spawn mode primarily used on Mac and Windows.
- Linux: fork, spawn
- Mac: spawn, fork
- Windows: spawn
Fixes #29
Fixes #70
=> Multiprocessing

pelican/plugins/photos/photos.py
=> Fix issue with format with exclude list

pelican/plugins/photos/photos.py
- When running the devserver pelican sends the initialized signal multiple times. This creates multiple process pools, but only the last one is usable for use.
- With this change we create the process pool before we start to process the first image and reuse this pool. Also we destroy the pool when pelican sends the finalized signal.
=> Change how the process pool is created

pelican/plugins/photos/photos.py
- Don't add missing galleries to gallery list
- Show additional information if gallery list is empty
- Remove gallery from output if missing
=> Handle missing galleries

pelican/plugins/photos/photos.py
- Add new function to convert images to rgb mode
- Apply the rgb mode converter for all JPEG output images in post processing
=> Add RGB mode converter

.github/workflows/main.yml
What an embarassing way to get PR #100
=> Fix a typo in the workflow

.github/workflows/main.yml, .pre-commit-config.yaml, examples/tasks.py, pelican/plugins/photos/photos.py, pelican/plugins/photos/test_photos.py, pyproject.toml, tasks.py
Added all of the ruff fixes that make sense, and re-enabled linting
=> Ruff linting

pyproject.toml
=> Use PDM backend to better build the namespace package

pelican/plugins/photos/photos.py
* Restore `typing` imports for base collections
* Make note_filename a classmethod instead of a property
=> Fix the typing changes that broke Python 3.8

tasks.py
Also brings the tasks up to current community best practices.
=> Switch Invoke tasks from Poetry to PDM

RELEASE.md
Add RELEASE file to prepare next release.
=> Prepare next release
